/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acmtodolist;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import problemdetails.JudgeDetail;
import problemdetails.SimpleProblem;

/**
 *
 * @author Kazi Nayeem
 */
public class AddProblemJPanelForm extends javax.swing.JPanel {

    static void refreshJudgeComboBox() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form AddProblemJPanelForm
     */
    public AddProblemJPanelForm() {
        initComponents();
        refreshJudgeSelectComboBox();
        initAddProblemJButton();
    }

    public void refreshJudgeSelectComboBox() {
        //add problem>>judgeSelectCombobox initialize
        String str[] = new String[JudgeDetail.getNumberOfJudge()];
        for (int i = 0; i < str.length; i++) {
            str[i] = JudgeDetail.getJudgeName(i);
        }
        judgeSelectJComboBox.setModel(new DefaultComboBoxModel(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judgeSelectJComboBox = new javax.swing.JComboBox();
        newProblemJudge = new javax.swing.JLabel();
        newProblemNumberJLabel = new javax.swing.JLabel();
        problemNoJTextField = new javax.swing.JTextField();
        newProblemNameJLabel = new javax.swing.JLabel();
        problemNameJTextField = new javax.swing.JTextField();
        addProblemJButton = new javax.swing.JButton();

        judgeSelectJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        judgeSelectJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newProblemJudge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newProblemJudge.setText("Judge Name : *");

        newProblemNumberJLabel.setText("Problem Number: *");

        newProblemNameJLabel.setText("Problem Name: *");

        addProblemJButton.setText("Add Problem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newProblemNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProblemNumberJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProblemJudge, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judgeSelectJComboBox, 0, 166, Short.MAX_VALUE)
                    .addComponent(problemNoJTextField)
                    .addComponent(problemNameJTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addComponent(addProblemJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProblemJudge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judgeSelectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(problemNoJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(newProblemNumberJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newProblemNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(problemNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(addProblemJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProblemJButton;
    private javax.swing.JComboBox judgeSelectJComboBox;
    private javax.swing.JLabel newProblemJudge;
    private javax.swing.JLabel newProblemNameJLabel;
    private javax.swing.JLabel newProblemNumberJLabel;
    private javax.swing.JTextField problemNameJTextField;
    private javax.swing.JTextField problemNoJTextField;
    // End of variables declaration//GEN-END:variables

    private void initAddProblemJButton() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        addProblemJButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                int judge = judgeSelectJComboBox.getSelectedIndex();
                String probID = problemNoJTextField.getText();
                String probName = problemNameJTextField.getText();
      
                if(judge == 0 || probID.equals("") || probName.equals("")){
                    JOptionPane.showMessageDialog(AcmToDoList.main_Window,"Invalid input", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                SimpleProblem obj = new SimpleProblem(JudgeDetail.getJudgeName(judge), probID, probName);
                obj.saveToFile();
                AcmToDoList.All_Problem_List.add(obj);
                AcmToDoList.main_Window.refreshProblemJTable();
            }
        });
        
    }
}
