/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acmtodolist;

import problemdetails.FullProblem;
import problemdetails.SimpleProblem;

/**
 *
 * @author Kazi Nayeem
 */
public class ProblemTabJPanelFrom extends javax.swing.JPanel {

    /**
     * Creates new form ProblemTabJPanelFrom initialize all components add
     * problem panel as left component of split pane add problem details panel
     * as right component of split pane
     */
    public ProblemTabJPanelFrom() {
        super();
        initComponents();

        problemDetailsPanel = new ProblemDetailJPanel();
        //problemDetailsPanel.setMaximumSize(new Dimension(20000, 320));
        jSplitPane1.setRightComponent(problemDetailsPanel);

        problemsTableJPanel = new ProblemsJPanelForm();
        jSplitPane1.setLeftComponent(problemsTableJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        jSplitPane1.setDividerLocation(600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private ProblemsJPanelForm problemsTableJPanel;
    private ProblemDetailJPanel problemDetailsPanel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * update the problem table
     */
    public void refreshProblemJTable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        problemsTableJPanel.refreshProblemJTable();
        //problemDetailsPanel.problemChange(null);
    }

    /**
     * problem update in problem details panel
     *
     * @param problem
     */
    void tableLastSelectedProblemUpdate(FullProblem problem) {
        ///throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        problemDetailsPanel.problemChange(problem);
    }

    /**
     * update topic list in topic panel update topic list in add problem panel
     * update topic list in problem Panel
     */
    void refreshTopicList() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        problemDetailsPanel.refreshTopicJCheckBox();
    }

    /**
     * problem tabel update for specific topic update the name of topic in
     * problem panel
     *
     * @param topicName
     */
    void refreshProblemJTable(String topicName) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        problemsTableJPanel.refreshProblemJTable(topicName);
        problemDetailsPanel.problemChange(null);
    }

    /**
     * problems tabel update for specific problem
     *
     * @param problem
     */
    void refreshProblemJTable(SimpleProblem problem) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        problemsTableJPanel.refreshProblemJTable(problem);
    }
}
