/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acmtodolist;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kazi Nayeem
 */
public class ProblemsJPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form ProblemsJPanelForm
     */
    static Object[][] problemInfoJTable; 
            
    public ProblemsJPanelForm() {
        super();
        initComponents();
        refreshProblemJTable();
    }

    public void refreshProblemJTable(){
        problemInfoJTable = new Object[AcmToDoList.All_Problem_List.size()][];
        for(int i = 0; i < AcmToDoList.All_Problem_List.size(); i++){
            problemInfoJTable[i] = (Object[]) AcmToDoList.All_Problem_List.get(i).getTableModel();
        }
        ProblemJTable.setModel(new DefaultTableModel(problemInfoJTable, tableColumsName));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        ProblemJTable = new javax.swing.JTable();
        allProblemJRadioButton = new javax.swing.JRadioButton();
        solvedProblemJRadioButton = new javax.swing.JRadioButton();
        unsolvedProblemJRadioButton = new javax.swing.JRadioButton();
        inqueueProblemJRadioButton = new javax.swing.JRadioButton();
        markAllProblemJButton = new javax.swing.JButton();
        toggleProblemJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputJTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputJTextArea = new javax.swing.JTextArea();
        removeQueueJButton = new javax.swing.JButton();
        addToQueueJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        markSolvedJButton = new javax.swing.JButton();
        markUnsolvedJButton = new javax.swing.JButton();
        inputOutputNameJLabel = new javax.swing.JLabel();
        inputOutputNoJLabel = new javax.swing.JLabel();
        inputOutputJComboBox = new javax.swing.JComboBox();
        problemJTableJPanel = new javax.swing.JPanel();

        ProblemJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(ProblemJTable);

        allProblemJRadioButton.setText("All Problems");

        solvedProblemJRadioButton.setText("Solved Problems");

        unsolvedProblemJRadioButton.setText("Unsolved Problems");

        inqueueProblemJRadioButton.setText("In-Queue Problems");

        markAllProblemJButton.setText("Mark all");

        toggleProblemJButton.setText("Toggle");

        inputJTextArea.setColumns(20);
        inputJTextArea.setRows(5);
        jScrollPane2.setViewportView(inputJTextArea);

        outputJTextArea.setColumns(20);
        outputJTextArea.setRows(5);
        jScrollPane1.setViewportView(outputJTextArea);

        removeQueueJButton.setText("Remove from Queue");

        addToQueueJButton.setText("Add To Queue");

        deleteJButton.setText("Delete");

        markSolvedJButton.setText("Mark as Solved");

        markUnsolvedJButton.setText("Mark as Unsolved");

        inputOutputNameJLabel.setText("Input and Output #:");

        inputOutputNoJLabel.setText("0");

        inputOutputJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout problemJTableJPanelLayout = new javax.swing.GroupLayout(problemJTableJPanel);
        problemJTableJPanel.setLayout(problemJTableJPanelLayout);
        problemJTableJPanelLayout.setHorizontalGroup(
            problemJTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        problemJTableJPanelLayout.setVerticalGroup(
            problemJTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markSolvedJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markUnsolvedJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToQueueJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeQueueJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allProblemJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(solvedProblemJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unsolvedProblemJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inqueueProblemJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(markAllProblemJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toggleProblemJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(problemJTableJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(inputOutputNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputOutputNoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(inputOutputJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allProblemJRadioButton)
                    .addComponent(solvedProblemJRadioButton)
                    .addComponent(unsolvedProblemJRadioButton)
                    .addComponent(inqueueProblemJRadioButton)
                    .addComponent(toggleProblemJButton)
                    .addComponent(markAllProblemJButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputOutputJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputOutputNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputOutputNoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(problemJTableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteJButton)
                            .addComponent(markSolvedJButton)
                            .addComponent(markUnsolvedJButton)
                            .addComponent(addToQueueJButton)
                            .addComponent(removeQueueJButton))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private final String[] tableColumsName = {"Judge","Problem No", "Problem Name", "Add Date", "Solve Date"};
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProblemJTable;
    private javax.swing.JButton addToQueueJButton;
    private javax.swing.JRadioButton allProblemJRadioButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTextArea inputJTextArea;
    private javax.swing.JComboBox inputOutputJComboBox;
    private javax.swing.JLabel inputOutputNameJLabel;
    private javax.swing.JLabel inputOutputNoJLabel;
    private javax.swing.JRadioButton inqueueProblemJRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton markAllProblemJButton;
    private javax.swing.JButton markSolvedJButton;
    private javax.swing.JButton markUnsolvedJButton;
    private javax.swing.JTextArea outputJTextArea;
    private javax.swing.JPanel problemJTableJPanel;
    private javax.swing.JButton removeQueueJButton;
    private javax.swing.JRadioButton solvedProblemJRadioButton;
    private javax.swing.JButton toggleProblemJButton;
    private javax.swing.JRadioButton unsolvedProblemJRadioButton;
    // End of variables declaration//GEN-END:variables
}
