/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SettingFrame;

import acmtodolist.AcmToDoList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import problemdetails.JudgeDetail;

/**
 *
 * @author Kazi Nayeem
 */
public final class JudgeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JudgeJPanel initialize all components in judge panel.
     * initialize addJudgeJButton action perform, initialize removeJudgeJButton
     * action perform.Update Judge Selection combo box
     */
    public JudgeJPanel() {
        super();
        initComponents();

        initAddJudgeJButton();
        initRemoveJudgeJButton();
        refreshJudgeSelectComboBox();
    }

    /**
     * get all judges name and update judge selection combo box in judge add or
     * remove panel
     */
    public void refreshJudgeSelectComboBox() {
        String str[] = new String[JudgeDetail.getNumberOfJudge()];
        for (int i = 0; i < str.length; i++) {
            str[i] = JudgeDetail.getJudgeName(i);
        }
        judgeSelectJComboBox.setModel(new DefaultComboBoxModel(str));
    }

    /**
     * initialize add button action perform
     */
    private void initAddJudgeJButton() {
        addJudgeJButton.addActionListener(new ActionListener() {

            /**
             * get name from newjudgetextfield add judge if didn't add before
             * output the status in addJudgeOutJLabel
             *
             * @param ae - Action event
             */
            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                if (!problemdetails.JudgeDetail.addJudge(newJudgeJTextField.getText())) {
                    //JOptionPane.showMessageDialog(null, "This Judge already added","Error" , JOptionPane.WARNING_MESSAGE);
                    addJudgeOutJLabel.setText("This Judge already added");

                } else {
                    addJudgeOutJLabel.setText("This Judge is added");
                }
                removeJudgeOutJLabel.setText("");
                AcmToDoList.main_Window.refreshJudgeComboBox();
                refreshJudgeSelectComboBox();
            }
        });
    }

    /**
     * add action listener for removeJudgeJButton
     */
    private void initRemoveJudgeJButton() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        removeJudgeJButton.addActionListener(new ActionListener() {

            /**
             * remove the specific judge that select in judgeSelectJComboBox and
             * update the status in removeJudgeJLabel
             *
             * @param ae - Action event
             */
            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                if (!problemdetails.JudgeDetail.removeJudge(judgeSelectJComboBox.getSelectedIndex())) {
                    //JOptionPane.showMessageDialog(null, "This Judge already added","Error" , JOptionPane.WARNING_MESSAGE);
                    removeJudgeOutJLabel.setText("The Judge cannot remove");

                } else {
                    removeJudgeOutJLabel.setText("The Judge removed");
                }
                addJudgeOutJLabel.setText("");

                AcmToDoList.main_Window.refreshJudgeComboBox();
                refreshJudgeSelectComboBox();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJudgeJLabel = new javax.swing.JLabel();
        newJudgeJTextField = new javax.swing.JTextField();
        addJudgeJButton = new javax.swing.JButton();
        addJudgeOutJLabel = new javax.swing.JLabel();
        judgeSelectJComboBox = new javax.swing.JComboBox();
        removeJudgeJLabel = new javax.swing.JLabel();
        removeJudgeJButton = new javax.swing.JButton();
        removeJudgeOutJLabel = new javax.swing.JLabel();

        newJudgeJLabel.setText("New Judge Name");

        addJudgeJButton.setText("Add Judge");

        removeJudgeJLabel.setText("Select to Delete Judge");

        removeJudgeJButton.setText("Remove Judge");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newJudgeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newJudgeJTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addJudgeOutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addJudgeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removeJudgeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(judgeSelectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removeJudgeOutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(removeJudgeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newJudgeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newJudgeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addJudgeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(addJudgeOutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judgeSelectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJudgeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeJudgeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJudgeOutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJudgeJButton;
    private javax.swing.JLabel addJudgeOutJLabel;
    private javax.swing.JComboBox judgeSelectJComboBox;
    private javax.swing.JLabel newJudgeJLabel;
    private javax.swing.JTextField newJudgeJTextField;
    private javax.swing.JButton removeJudgeJButton;
    private javax.swing.JLabel removeJudgeJLabel;
    private javax.swing.JLabel removeJudgeOutJLabel;
    // End of variables declaration//GEN-END:variables

}
