/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SettingFrame;

import acmtodolist.AcmToDoList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import problemdetails.TopicClass;
import problemdetails.TopicDetail;

/**
 *
 * @author Kazi Nayeem
 */
public class TopicSettingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TopicSettingJPanel initialize all components in topic
     * panel. initialize addTopicJButton action perform, initialize
     * removeTopicJButton action perform.Update Topic Selection combo box
     */
    public TopicSettingJPanel() {
        super();
        initComponents();
        initAddTopicJButton();
        initRemoveTopicJButton();
        refreshTopicList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTopicNameJLabel = new javax.swing.JLabel();
        newTopicJTextField = new javax.swing.JTextField();
        addTopicJButton = new javax.swing.JButton();
        addTopicOutJLabel = new javax.swing.JLabel();
        removeTopicOutJLabel = new javax.swing.JLabel();
        deleteTopicJLabel = new javax.swing.JLabel();
        topicSelectJComboBox = new javax.swing.JComboBox();
        removeTopicJButton = new javax.swing.JButton();

        newTopicNameJLabel.setText("New Topic Name");

        addTopicJButton.setText("Add Topic");

        deleteTopicJLabel.setText("Remove Topic");

        removeTopicJButton.setText("Remove Topic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addTopicOutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addTopicJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newTopicNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newTopicJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeTopicOutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeTopicJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteTopicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topicSelectJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTopicNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTopicJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTopicJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTopicOutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTopicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicSelectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(removeTopicOutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(removeTopicJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String topicList[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTopicJButton;
    private javax.swing.JLabel addTopicOutJLabel;
    private javax.swing.JLabel deleteTopicJLabel;
    private javax.swing.JTextField newTopicJTextField;
    private javax.swing.JLabel newTopicNameJLabel;
    private javax.swing.JButton removeTopicJButton;
    private javax.swing.JLabel removeTopicOutJLabel;
    private javax.swing.JComboBox topicSelectJComboBox;
    // End of variables declaration//GEN-END:variables

    /**
     * initialize add button action perform
     */
    private void initAddTopicJButton() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

        addTopicJButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                int result = TopicDetail.addTopic(newTopicJTextField.getText());

                if (result == TopicClass.SUCCESSFULLY_ADDED) {
                    addTopicOutJLabel.setText("Successfully Added");
                    refreshTopicList();
                    AcmToDoList.main_Window.refreshTopicList();

                } else if (result == TopicClass.ALREADY_TOPIC_ADDED) {
                    addTopicOutJLabel.setText("This topic already added");
                } else if (result == TopicClass.FORMAT_ERROR) {
                    addTopicOutJLabel.setText("Name invalid");
                } else if (result == TopicClass.ERROR_IN_ADDING) {
                    addTopicOutJLabel.setText("Can\'t Added");
                }

                removeTopicOutJLabel.setText("");
            }
        });
    }

    /**
     * add action listener for removeRemoveJButton
     */
    private void initRemoveTopicJButton() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        removeTopicJButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                int result = TopicDetail.removeTopic(topicSelectJComboBox.getSelectedItem().toString());

                if (result == TopicClass.SUCCESSFULLY_REMOVE) {
                    removeTopicOutJLabel.setText("Successfully remove");
                    refreshTopicList();
                    AcmToDoList.main_Window.refreshTopicList();

                } else if (result == TopicClass.TOPIC_NOT_FOUND) {
                    removeTopicOutJLabel.setText("This topic not found");
                } else if (result == TopicClass.FORMAT_ERROR) {
                    removeTopicOutJLabel.setText("Name invalid");
                } else if (result == TopicClass.ERROR_IN_ADDING) {
                    removeTopicOutJLabel.setText("Can\'t Delete");
                }

                addTopicOutJLabel.setText("");
            }
        });

    }

    /**
     * get all topic name and update topic selection combo box in topic add or
     * remove panel
     */
    private void refreshTopicList() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

        topicList = TopicDetail.getTopicNameList();
        topicList[0] = TopicDetail.SELECT_ONE;

        topicSelectJComboBox.setModel(new DefaultComboBoxModel(topicList));
    }
}
